[package]
name = "nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.8.0"
lazy_static = "1.5.0"
rand = "0.9.0"
sdl2 = "0.37.0"
